blank_issues_enabled: false
contact_links:
  - name: 🙋 Questions & Support
    url: https://github.com/Kenzo-Wada/thanks-stars/discussions
    about: Please start a discussion for general questions or support requests.
